### ISSUE TITLE
put a link to the hosted version and screenshots in README?

### ISSUE THREAD

**Issue by n1trux** [mezod/multikanban#1]
As somebody [stumbling upon](http://www.reddit.com/r/selfhosted/comments/33uhbo/multikanban_a_simple_kanban_for_multiple_personal/) this software, wouldn't it be nice for the README to include a link to the [hosted](http://www.multikanban.com/) version and a screenshot like it's there? This way the people could actually see what this is about.

**Comment by mezod** [comment]
done! thanks for the feedback :)
