### ISSUE TITLE
How to run properly?

### ISSUE THREAD

**Issue by ghost** [mezod/multikanban#2]
Hi,

I just tried to set multikanban up, but I can't get it working. When I browse to the url all I get is "App started" in the console and a blank page.

Can you please share detailed install instructions?

**Comment by mezod** [comment]
did you also clone de multikanban-api and set up the mysql database? See if this brings some light: http://blog.joanboixados.com/deploying-multikanban/ or let me know again!

**Comment by ghost** [comment]
That was the missing peace, thanks! Maybe you should link it in the Readme? :)
