### ISSUE TITLE
Wiki Review

### ISSUE THREAD

**Issue by Kickball** [mezod/multikanban#3]
Mezod,

As there was no real getting started guide I wrote the steps I took to try to install multikanban on this repo's [wiki](https://github.com/mezod/multikanban/wiki/Gettings-Started).

Can you review it and edit it as needed?

Thanks,
Kickball

**Comment by mezod** [comment]
Hey Kickball, great job! It looks good, the only tricky part is actually setting the paths relative to how you set it in your computer, and you did that right! I had defined some virtual hosts that just mess up with everything. Also in the production version I put the API inside the frontend project to avoid having to use CORS... I'm curious, where did you find about this repo?

**Comment by Kickball** [comment]
Which repo? I found this repo linked on [/r/selfhosted](http://www.reddit.com/r/selfhosted/comments/33uhbo/multikanban_a_simple_kanban_for_multiple_personal/).

The repo I used for the backend was [multikanban-api](https://github.com/mezod/multikanban-api), although I was having problems with it, as you can see with my issue on that repo.

I just listed the steps which I followed, if there is a better way to do them then please feel free to edit the wiki page.

**Comment by mezod** [comment]
Oh cool. Yeah I answered there! I'll review it more in detail when I find the time but it looked pretty good, I attached you how I deployed it to the serv http://blog.joanboixados.com/deploying-multikanban/

**Comment by Kickball** [comment]
@mezod have you been able to find time to checkover the wiki?

**Comment by Kickball** [comment]
Closing this out as a Wiki article has been created and the project is mostly stale.
